from __future__ import annotations

from .types import RealCupResults

REAL_CUP_RESULTS: RealCupResults = [
    # Cup 1 — China
    {
        "Mudda": 1000,
        "Carl Jr.": 80,
        "Massa": 400,
        "Binkss": 700,
        "Wosile": 64,
        "GranaDy": 600,
        "Bren": 48,
        "Nayko": 92,
        "Epos": 44,
        "Otaaaq": 2,
        "Gwen": 500,
        "Xerar": 20,
        "Scrapie": 26,
        "eLconn21": 56,
        "Heav": 300,
        "Legu": 36,
        "Whizzy": 200,
        "josh1248": 24,
        "jdon": 100,
        "pusztitopako": 88,
        "Pac": 18,
        "Soulja": 68,
        "Cocow": 76,
        "Stufts": 96,
        "Melioo": 20,
        "Azion": 30,
        "NiTech": 6,
        "RotakeR": 22,
        "Affi": 72,
        "Glast": 60,
        "Snow": 56,
        "Hyll": 60,
        "Letzter": 84,
        "Charles": 40,
        "Razii": 52,
        "mime": 40,
        "Flimsy": 16,
        "neon": 30,
        "Jan123405": 16,
        "Worker": 32,
        "Spammiej": 64,
        "Eria": 22,
        "tween": 44,
        "Tjalic": 32,
        "J_Swag": 12,
        "Cemko": 52,
        "L1ngo": 10,
        "Yekcosdo": 28,
        "bestie77": 14,
        "Dionysos": 4,
        "noiszia": 48,
        "ender": 10,
        "Dog": 24,
        "Feed": 14,
        "Neal": 12,
        "Magorian": 28,
        "Mobbi": 26,
        "Huso": 36,
        "Panda": 8,
        "purple": 18,
        "Ener": 8,
        "Javzo": 6,
        "Spark": 4,
        "V1NCH": 2,
    },
    # Cup 2 — France
    {
        "Mudda": 1000,
        "Carl Jr.": 500,
        "Massa": 6,
        "Binkss": 100,
        "Wosile": 20,
        "GranaDy": 64,
        "Bren": 48,
        "Nayko": 700,
        "Epos": 400,
        "Otaaaq": 72,
        "Gwen": 8,
        "Xerar": 600,
        "Scrapie": 56,
        "eLconn21": 88,
        "Heav": 68,
        "Legu": 300,
        "Whizzy": 24,
        "josh1248": 200,
        "jdon": 26,
        "pusztitopako": 84,
        "Pac": 44,
        "Soulja": 30,
        "Cocow": 22,
        "Melioo": 12,
        "Azion": 92,
        "NiTech": 64,
        "RotakeR": 96,
        "Affi": 76,
        "Glast": 52,
        "Snow": 60,
        "Letzter": 28,
        "NuPrime": 10,
        "Charles": 52,
        "Razii": 40,
        "mime": 44,
        "Flimsy": 24,
        "neon": 18,
        "Jan123405": 80,
        "Worker": 56,
        "Molle": 60,
        "tween": 32,
        "Tjalic": 36,
        "J_Swag": 20,
        "Birdie": 40,
        "Cemko": 16,
        "L1ngo": 14,
        "Jan": 36,
        "Evon": 48,
        "Kakne": 4,
        "bestie77": 32,
        "Dog": 28,
        "Cinxsss": 26,
        "Neal": 30,
        "Magorian": 10,
        "Mobbi": 14,
        "key": 18,
        "raizo": 22,
        "oNio": 16,
        "baiwack": 2,
        "Narcor": 8,
        "Liquid": 12,
        "Chamow": 6,
        "Intax": 4,
        "Demotivator13": 2,
    },
    # Cup 3 — USA
    {
        "Mudda": 24,
        "Carl Jr.": 52,
        "Massa": 400,
        "Binkss": 10,
        "Wosile": 1000,
        "GranaDy": 200,
        "Bren": 700,
        "Nayko": 18,
        "Epos": 300,
        "Otaaaq": 600,
        "Gwen": 68,
        "Xerar": 52,
        "Scrapie": 500,
        "eLconn21": 8,
        "Tona": 26,
        "Heav": 64,
        "Legu": 60,
        "Whizzy": 12,
        "josh1248": 76,
        "jdon": 84,
        "pusztitopako": 92,
        "Pac": 96,
        "Soulja": 48,
        "Cocow": 72,
        "Melioo": 100,
        "Azion": 8,
        "NiTech": 28,
        "RotakeR": 22,
        "Affi": 6,
        "Glast": 2,
        "Snow": 40,
        "Hyll": 44,
        "Letzter": 22,
        "NuPrime": 80,
        "Charles": 36,
        "Razii": 56,
        "mime": 32,
        "Flimsy": 32,
        "neon": 4,
        "Worker": 30,
        "Spammiej": 40,
        "Eria": 88,
        "tween": 4,
        "J_Swag": 60,
        "Birdie": 24,
        "L1ngo": 56,
        "Jan": 14,
        "Evon": 14,
        "Tricky": 64,
        "Yekcosdo": 36,
        "Dionysos": 44,
        "MimoJr": 48,
        "Goldennugg3t": 40,
        "Magorian": 2,
        "Richie1308": 30,
        "Tomczan": 28,
        "Haedra": 26,
        "Kurisu-tina": 16,
        "PauLL": 20,
        "Pika": 20,
        "AwayFridish": 18,
        "Panda": 10,
        "Barbos": 16,
        "Narcor": 6,
        "Brinkenn": 12,
    },
    # Cup 4 — Brazil
    {
        "Mudda": 40,
        "Carl Jr.": 1000,
        "Massa": 700,
        "Binkss": 600,
        "Wosile": 300,
        "GranaDy": 56,
        "Bren": 92,
        "Epos": 8,
        "Otaaaq": 26,
        "Gwen": 100,
        "Scrapie": 36,
        "eLconn21": 400,
        "Tona": 500,
        "Heav": 32,
        "Legu": 44,
        "Whizzy": 200,
        "josh1248": 88,
        "jdon": 68,
        "pusztitopako": 2,
        "Pac": 72,
        "Soulja": 60,
        "Cocow": 22,
        "Stufts": 96,
        "Melioo": 52,
        "Azion": 52,
        "NiTech": 80,
        "RotakeR": 28,
        "Affi": 10,
        "Glast": 48,
        "Snow": 4,
        "Hyll": 48,
        "Letzter": 18,
        "NuPrime": 60,
        "Charles": 20,
        "mime": 26,
        "Flimsy": 64,
        "neon": 76,
        "Jan123405": 30,
        "Molle": 56,
        "Spammiej": 12,
        "tween": 22,
        "Tjalic": 32,
        "J_Swag": 4,
        "Birdie": 24,
        "Bimy": 84,
        "Cemko": 14,
        "L1ngo": 2,
        "Jan": 30,
        "Evon": 6,
        "Kakne": 64,
        "bestie77": 16,
        "Dionysos": 12,
        "noiszia": 8,
        "ender": 44,
        "Cinxsss": 24,
        "Feed": 28,
        "Aurel": 36,
        "key": 10,
        "Kurisu-tina": 6,
        "link": 20,
        "Ricso5": 18,
        "baiwack": 14,
        "TaMaR": 16,
    },
    # Cups 5–10 — not yet played
    None,
    None,
    None,
    None,
    None,
    None,
]

REAL_PLAYERS: list[tuple[str, str]] = [
    ("Mudda", "Australia"),
    ("Carl Jr.", "Canada"),
    ("Massa", "Germany"),
    ("Binkss", "France"),
    ("Wosile", "France"),
    ("GranaDy", "Germany"),
    ("Bren", "France"),
    ("Nayko", "France"),
    ("Epos", "United Kingdom"),
    ("Otaaaq", "France"),
    ("Gwen", "France"),
    ("Xerar", "France"),
    ("Scrapie", "Belgium"),
    ("eLconn21", "Czechia"),
    ("Tona", "France"),
    ("Heav", "France"),
    ("Legu", "France"),
    ("Whizzy", "United Kingdom"),
    ("josh1248", "United Kingdom"),
    ("jdon", "United Kingdom"),
    ("pusztitopako", "Hungary"),
    ("Pac", "United Kingdom"),
    ("Soulja", "Belgium"),
    ("Cocow", "France"),
    ("Stufts", "Netherlands"),
    ("Melioo", "France"),
    ("Azion", "France"),
    ("NiTech", "Russia"),
    ("RotakeR", "Poland"),
    ("Affi", "Switzerland"),
    ("Glast", "France"),
    ("Snow", "France"),
    ("Hyll", "Czechia"),
    ("Letzter", "Germany"),
    ("NuPrime", "Germany"),
    ("Charles", "Colombia"),
    ("Razii", "Croatia"),
    ("mime", "Poland"),
    ("Flimsy", "United States"),
    ("neon", "Poland"),
    ("Jan123405", "Slovenia"),
    ("Worker", "France"),
    ("Molle", "Sweden"),
    ("Spammiej", "Netherlands"),
    ("Eria", "Belgium"),
    ("tween", "Slovakia"),
    ("Tjalic", "France"),
    ("J_Swag", "New Zealand"),
    ("Birdie", "Turkey"),
    ("Bimy", "Russia"),
    ("Cemko", "Turkey"),
    ("L1ngo", "Canada"),
    ("Jan", "Germany"),
    ("Evon", "Poland"),
    ("Kakne", "United States"),
    ("Tricky", "France"),
    ("Yekcosdo", "Portugal"),
    ("bestie77", "Czechia"),
    ("Dionysos", "France"),
    ("noiszia", "Argentina"),
    ("ender", "Morocco"),
    ("Dog", "Germany"),
    ("Cinxsss", "Norway"),
    ("MimoJr", "France"),
    ("Feed", "France"),
    ("Neal", "United States"),
    ("Goldennugg3t", "Germany"),
    ("Magorian", "Poland"),
    ("Mobbi", "Germany"),
    ("Aurel", "France"),
    ("Huso", "Turkey"),
    ("Richie1308", "France"),
    ("key", "Poland"),
    ("Tomczan", "Poland"),
    ("Haedra", "France"),
    ("Kurisu-tina", "Italy"),
    ("raizo", "Slovakia"),
    ("link", "France"),
    ("PauLL", "Portugal"),
    ("Pika", "Portugal"),
    ("AwayFridish", "Italy"),
    ("Panda", "France"),
    ("purple", "Germany"),
    ("Ricso5", "Hungary"),
    ("baiwack", "New Zealand"),
    ("Barbos", "Germany"),
    ("oNio", "Germany"),
    ("TaMaR", "Israel"),
    ("Narcor", "Poland"),
    ("Brinkenn", "Sweden"),
    ("Liquid", "United States"),
    ("Ener", "France"),
    ("Chamow", "France"),
    ("Javzo", "Netherlands"),
    ("Intax", "Norway"),
    ("Spark", "India"),
    ("Demotivator13", "Poland"),
    ("V1NCH", "France"),
]


def parse_standings(text: str) -> list[tuple[str, str]]:
    """Parse raw standings text into [(name, country), ...].

    Expects lines like: '1. PlayerName CountryName' or 'PlayerName CountryName'.
    Handles multi-word countries: 'United Kingdom', 'United States', 'New Zealand'.
    """
    multi_word_countries = {
        "United Kingdom",
        "United States",
        "New Zealand",
    }
    results: list[tuple[str, str]] = []
    for line in text.splitlines():
        line = line.strip()
        if not line:
            continue
        # Strip optional leading rank number
        if line[0].isdigit():
            parts = line.split(None, 1)
            if len(parts) == 2:
                line = parts[1].lstrip(". ")
        tokens = line.split()
        if len(tokens) < 2:
            continue
        # Try two-word country first
        for country_words in (2, 1):
            if len(tokens) > country_words:
                name = " ".join(tokens[:-country_words])
                country = " ".join(tokens[-country_words:])
                if country_words == 1 or country in multi_word_countries:
                    results.append((name, country))
                    break
    return results
